# Google Sheet config
sheet_id = "1ptIhCIjVgFzinzRo24HjiKLeLxwXjQwlIP1AFcz6R2A"
sheet_name = "Registrations"

[gcp_service_account]
type = "service_account"
project_id = "cba-hamos"
private_key_id = "980a1cb1acb4efec2fa3ce205e033c72263d8ff4"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4sozUODMhaNc9
sSXcAmvmQQsbJkFpt1qp6QsEXuDgDHVc3lgJZVPZI2/SxTXwDDEtgeCuh9cR02H/
yeqww9LKHsldHawTLFeJQOzWNWR11VRXSOX8KrXeQVsPd5q0Pso6k5kgMjJbnJi8
… (rest of your key, with actual line breaks) …
-----END PRIVATE KEY-----
"""
client_email = "hamos-admin@cba-hamos.iam.gserviceaccount.com"
client_id = "111149466916148573516"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hamos-admin%40cba-hamos.iam.gserviceaccount.com"

[admin_credentials]
HAM1 = "christbase22"
HAM2 = "christbase23"
