[gcp_service_account]
type = "service_account"
project_id = "cba-hamos"
private_key_id = "980a1cb1acb4efec2fa3ce205e033c72263d8ff4"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC4sozUODMhaNc9
sSXcAmvmQQsbJkFpt1qp6QsEXuDgDHVc3lgJZVPZI2/SxTXwDDEtgeCuh9cR02H/
yeqww9LKHsldHawTLFeJQOzWNWR11VRXSOX8KrXeQVsPd5q0Pso6k5kgMjJbnJi8
+RUUFxr2WB6KnccdZIVTVsftBIWTmU/vvd2JmWX8YhWt7ATSzYmKsml9ug9S6kS3
1fqAtvcn76bqucXY63rOsGeCDfVUe+1EnTDqSS2M7V2RYOjQLk0Ap1Ma0o65W8qs
W/LqHCkN/92F6yDQHM3oc8TuQbu62uIb6l48zPimuTLR3fnoM2bULBtnl8sQOGxI
V8Ho+dbnAgMBAAECggEANu2u8UxXdHesD6ZX9pLnyP4OEgByEsEbXw22H5Ih+a/q
1XgwoXa3lYuy7XGGJYJSu9B05CL1BNGjQwGnYPOUBFVcmGtDKh6VV/XtmZUeb+bG
YwEEmNaQ6Ozx6mstIK7N0Nblgsw66sDrMcQ4DxYCCEJTrvDWbzjeZ9cWtTgTi73a
kdAlu8/2HotiZdTiTytg9U19c/ixOkuDglNYEBN8Tjlw+0iKBIIlFehmLbI0Bpoa
8EUvbC4gr83/nBR5DlnA8Z0L/ElcXWoBVPBi1UUl0KkenL2QpUCeKdF5Qqw6qoHd
u/gTRQ6wPV7TmVWSxkTBm0+CbBa/VBVIOEeZlbVRXQKBgQDnN6yrsU1VG/ekRFu1
UszGr1fN/0dvVjwCLz3Tgwg7OknHjVVMnRZJJuRNhcloJf2U/EkSvoSx0eaRlSqN
krDoKLHxS3m+kmZ2uCoEv0Mp7b8xEtMGajl7/6NeSGBIKoRn9oTcOIxpRC7FP42N
jhuS8QyvZKaid2ALJeDiTa9rowKBgQDMfmxQvp3Nr70osJXbqkztU0D8KJds7Spi
bS8x9ZqozuIqCeVBIO5VFdoxnQK3yvbfv3bh81jfjfCI599PxPnLYXBEo+L0TTOQ
IysH9jD25/97plmAdnyVCo4YsTI+lr8/qpqFxyaLCV55NOlmiryW/NvE4rASNhq5
k18sgXMb7QKBgEOZ0oEsSHjewWuklM+R0s8wStKulVsm8kqNN11UzR5L73BJkSvi
LbbbiRplSDqMCPT7Qf4Z97/pp6je3N8hiVmHNGdg8spWEWEafSaAKQnkOecGIu6Y
NhBb8I7LSGMxEx82QygD3IGWbro6148Qgl1W3qeVHOcZUdpQi8x+fBBTAoGAVsTN
8PTwwHXxLXLAI5T/TzQkPtp6Zh27/keV3vz3wukFzhCk1h3DAxdineqhXJsiZY44
Q2eeLj1r8qtwdch+tW2C1Z00j7SyTFafy6EK5blLDoxnLbsY4aS45oFJcIVGYR1i
s6DtGdG/5G4vGvODUg24srH9Q7zxWgzONXQ4A4ECgYBZDvWc99Kxe2lNCQP9rkxB
eqqLJXKmWmvadiPQ8vWdVg8n6AmiMuWRU0v3qj9s+S4suGJWlj4pLnHSvgtHgxaB
ibQMblKaHBBl9z5/8uwhxikRGkPEIebyfrQHJD6BB1IGcL9CikmOJn3xDFsOt/Cw
87+ch4/KYjhvqS/V8bXkTQ==
-----END PRIVATE KEY-----
"""
client_email = "hamos-admin@cba-hamos.iam.gserviceaccount.com"
client_id = "111149466916148573516"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hamos-admin%40cba-hamos.iam.gserviceaccount.com"

# Google Sheet config
sheet_id = "1ptIhCIjVgFzinzRo24HjiKLeLxwXjQwlIP1AFcz6R2A"
sheet_name = "Registrations"

[admin_credentials]
HAM1 = "christbase22"
HAM2 = "christbase23"
